name: @NAME@
targets:
  @NAME@:
    platform: iOS
    type: application
    sources:
      - path: src
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.orastron.@BUNDLE_NAME@
        SWIFT_OBJC_BRIDGING_HEADER: src/app-Bridging-Header.h
        HEADER_SEARCH_PATHS:
          - ../../../src
          - ../../../../common/ios
          - ../../../../../include
          - ../../../../../../miniaudio
    info:
      path: Info.plist
      properties:
        NSMicrophoneUsageDescription: Audio input access needed to run the example
